// API client for the PRAHARI backend, with a self-contained STATIC mode.
//
//  * Dynamic mode (default): talks to the live FastAPI backend. Set
//    VITE_API_BASE_URL for a deployed backend, or use the dev proxy locally.
//  * Static mode (VITE_STATIC_DEMO=1): reads pre-computed JSON bundled in
//    /public/demo, so the deployed site runs with no backend to keep alive —
//    it can never go down during judging. The JSON is the exact backend output
//    (generated by backend/scripts/export_demo.py).
const BASE = import.meta.env.VITE_API_BASE_URL || ''
const STATIC = import.meta.env.VITE_STATIC_DEMO === '1'

async function jget(url) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`GET ${url} → ${res.status}`)
  return res.json()
}
const demo = (p) => jget(`${import.meta.env.BASE_URL}demo/${p}`)

async function get(path) { return jget(`${BASE}${path}`) }
async function post(path, body) {
  const res = await fetch(`${BASE}${path}`, {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body),
  })
  if (!res.ok) throw new Error(`POST ${path} → ${res.status}`)
  return res.json()
}

// Static caches (fetched once).
let _events = null, _briefs = null, _interdictions = null

// Client-side Ask-PRAHARI mirroring the backend's deterministic retrieval.
const STOP = new Set(['the', 'a', 'an', 'of', 'for', 'to', 'and', 'or', 'is', 'are', 'what',
  'how', 'why', 'in', 'on', 'about', 'does', 'do', 'with', 'bangladesh'])
async function staticAsk(question, language) {
  _events = _events || await demo('drishti/events.json')
  const qtok = [...new Set(question.toLowerCase().replace(/\?/g, ' ').split(/\s+/))]
    .filter((w) => w.length > 2 && !STOP.has(w))
  const scoreOf = (s) => {
    const hay = [s.event.title, s.event.summary, ...s.event.actors, ...s.event.sectors].join(' ').toLowerCase()
    return qtok.reduce((n, w) => n + (hay.includes(w) ? 1 : 0), 0)
  }
  const matches = _events.events.map((s) => [scoreOf(s), s]).filter(([n]) => n > 0)
    .sort((a, b) => b[0] - a[0]).slice(0, 4).map(([, s]) => s)

  const top = matches[0]
  let answer
  if (!top) {
    answer = language === 'bn'
      ? 'এই মুহূর্তে DRISHTI ফিডে এই প্রশ্নের সাথে সরাসরি সম্পর্কিত কোনো ঘটনা পাওয়া যায়নি।'
      : 'No event directly related to this question is currently in the DRISHTI feed.'
  } else if (language === 'bn') {
    answer = `সবচেয়ে প্রাসঙ্গিক ঘটনা: “${top.event.title}” (বাংলাদেশ প্রাসঙ্গিকতা স্কোর ${Math.round(top.relevance_score)}/১০০)। বিস্তারিত সুপারিশের জন্য সংশ্লিষ্ট ঘটনার Do/Avoid ব্রিফ দেখুন।`
  } else {
    answer = `The most relevant event is “${top.event.title}” (Bangladesh Relevance ${Math.round(top.relevance_score)}/100, severity ${top.severity}). ${top.event.summary} Open that event's Do/Avoid brief for specific recommendations.`
  }
  const conf = Math.min(0.9, 0.3 + matches.length * 0.2)
  return {
    question, language, answer,
    referenced_events: matches.map((s) => s.event.id),
    evidence: matches.map((s) => ({ source: s.event.source, detail: s.event.title, url: s.event.url })),
    meta: { confidence: conf, confidence_label: conf >= 0.75 ? 'high' : conf >= 0.5 ? 'medium' : 'low', model_version: 'drishti-ask-static/0.1.0' },
    answer_source: 'deterministic',
  }
}

export const api = {
  // DRISHTI
  events: async ({ sector, severity, minScore } = {}) => {
    if (STATIC) {
      const d = await demo('drishti/events.json')
      let ev = d.events
      if (sector) ev = ev.filter((s) => s.event.sectors.includes(sector))
      if (severity) ev = ev.filter((s) => s.severity === severity)
      if (minScore) ev = ev.filter((s) => s.relevance_score >= minScore)
      return { ...d, events: ev, total: ev.length }
    }
    const q = new URLSearchParams()
    if (sector) q.set('sector', sector)
    if (severity) q.set('severity', severity)
    if (minScore) q.set('min_score', minScore)
    return get(`/api/drishti/events?${q.toString()}`)
  },
  brief: async (eventId, language = 'en') => {
    if (STATIC) {
      _briefs = _briefs || await demo('drishti/briefs.json')
      return _briefs[`${eventId}:${language}`] || _briefs[`${eventId}:en`]
    }
    return get(`/api/drishti/events/${encodeURIComponent(eventId)}/brief?language=${language}`)
  },
  ask: async (question, language = 'en') =>
    STATIC ? staticAsk(question, language) : post('/api/drishti/ask', { question, language }),

  // RAKKHOK
  readiness: () => (STATIC ? demo('rakkhok/readiness.json') : get('/api/rakkhok/readiness')),
  assets: (force) => (STATIC ? demo('rakkhok/assets.json') : get(`/api/rakkhok/assets${force ? `?force=${force}` : ''}`)),
  rulRanking: (limit = 8) => (STATIC ? demo('rakkhok/rul-ranking.json') : get(`/api/rakkhok/rul-ranking?limit=${limit}`)),
  fleetAlerts: () => (STATIC ? demo('rakkhok/alerts.json') : get('/api/rakkhok/alerts')),

  // SHOMUDRO
  picture: () => (STATIC ? demo('shomudro/picture.json') : get('/api/shomudro/picture')),
  interdiction: async (targetId) => {
    if (STATIC) {
      _interdictions = _interdictions || await demo('shomudro/interdictions.json')
      return _interdictions[targetId]
    }
    return get(`/api/shomudro/interdiction/${encodeURIComponent(targetId)}`)
  },
}
